// aiRecommendations.js
// Main-process module: derives a short list of concrete, actionable
// recommendations from data the other AI Improvement Framework modules have
// already actually recorded (aiMetrics call history, complianceMonitor's
// guardrail-trend data, dependencyAuditor's version check). Nothing here is
// generated by an AI model and nothing is invented - every recommendation
// traces back to a real number crossing a fixed, documented threshold, and
// every recommendation object carries a `basis` field showing exactly which
// real numbers produced it. A project with no recorded data yet gets an
// honest "not enough data" entry, never a fabricated suggestion.

const aiMetrics = require('./aiMetrics');
const complianceMonitor = require('./complianceMonitor');
const dependencyAuditor = require('./dependencyAuditor');

const MIN_CALLS_FOR_FAILURE_RATE = 5;
const HIGH_FAILURE_RATE_PCT = 20;
const MIN_SAMPLES_FOR_LATENCY_COMPARISON = 5;
const SLOWER_MODEL_RATIO = 2; // p90 at least 2x a comparably-reliable model's p90

function pushRec(list, rec) {
  list.push({ severity: rec.severity, title: rec.title, detail: rec.detail, basis: rec.basis });
}

/**
 * Returns { ok, recommendations: [...], generatedAt }. Read-only - never
 * writes anything, never triggers a new AI call, guardrail run, or network
 * request beyond what dependencyAuditor already does as a best-effort check.
 */
async function getRecommendations(projectPath) {
  if (!projectPath) return { ok: false, error: 'No project folder.' };

  const recommendations = [];

  const metricsSummary = aiMetrics.getMetricsSummary(projectPath);
  if (metricsSummary.totalCalls === 0) {
    pushRec(recommendations, {
      severity: 'info',
      title: 'No AI call data recorded yet',
      detail: 'Once this project makes real AI calls through Nexus (or calls aiFwRecordMetric itself), recommendations here will be based on that real usage.',
      basis: 'aiMetrics: totalCalls = 0',
    });
  } else {
    for (const m of metricsSummary.byModel) {
      if (m.calls >= MIN_CALLS_FOR_FAILURE_RATE && m.successRate !== null && (100 - m.successRate) >= HIGH_FAILURE_RATE_PCT) {
        pushRec(recommendations, {
          severity: 'high',
          title: `${m.model} is failing ${(100 - m.successRate).toFixed(1)}% of calls`,
          detail: `${m.calls} recorded calls, ${m.successRate}% success rate. Worth checking recent error messages in the metrics history before relying on this model further.`,
          basis: `aiMetrics: model=${m.model}, calls=${m.calls}, successRate=${m.successRate}%`,
        });
      }
    }

    // Latency comparison: only compare models with enough samples each, and
    // only recommend a swap toward a model that is not itself unreliable.
    const percentiles = aiMetrics.getLatencyPercentiles(projectPath);
    const eligible = percentiles.filter((p) => p.samples >= MIN_SAMPLES_FOR_LATENCY_COMPARISON);
    for (const slow of eligible) {
      const slowSummary = metricsSummary.byModel.find((m) => m.model === slow.model);
      if (!slowSummary || slowSummary.successRate === null || slowSummary.successRate < 80) continue;
      const faster = eligible
        .filter((p) => p.model !== slow.model && p.p90 * SLOWER_MODEL_RATIO <= slow.p90)
        .sort((a, b) => a.p90 - b.p90)[0];
      if (faster) {
        const fastSummary = metricsSummary.byModel.find((m) => m.model === faster.model);
        if (fastSummary && fastSummary.successRate !== null && fastSummary.successRate >= slowSummary.successRate - 5) {
          pushRec(recommendations, {
            severity: 'medium',
            title: `${faster.model} is consistently faster than ${slow.model} at similar reliability`,
            detail: `p90 latency ${faster.p90}ms vs ${slow.p90}ms (${slow.samples} vs ${faster.samples} recorded calls), success rate ${fastSummary.successRate}% vs ${slowSummary.successRate}%.`,
            basis: `aiMetrics.getLatencyPercentiles: ${slow.model} p90=${slow.p90}ms (n=${slow.samples}), ${faster.model} p90=${faster.p90}ms (n=${faster.samples})`,
          });
        }
      }
    }
  }

  const compliance = complianceMonitor.getComplianceStatus(projectPath);
  if (!compliance.hasGuardrailData) {
    pushRec(recommendations, {
      severity: 'info',
      title: 'No guardrail/safety test results yet',
      detail: 'Add an npm script matching "guardrail", "contract", "safety", "compliance", or "constitution" in this project and run it from AI Tools → Guardrail Testing to start tracking compliance.',
      basis: 'complianceMonitor: hasGuardrailData = false',
    });
  } else if (compliance.trend === 'regressing') {
    pushRec(recommendations, {
      severity: 'high',
      title: 'Guardrail compliance score is regressing',
      detail: `Latest score ${compliance.latestScore}%, down from ${compliance.previousScore}% on the previous run (${compliance.latestRunAt}).`,
      basis: `complianceMonitor: latestScore=${compliance.latestScore}, previousScore=${compliance.previousScore}, trend=regressing`,
    });
  } else if (compliance.latestScore !== null && compliance.latestScore < 100) {
    pushRec(recommendations, {
      severity: 'medium',
      title: `Guardrail suite is at ${compliance.latestScore}%, not fully passing`,
      detail: `Latest run: ${compliance.latestScore}% (trend: ${compliance.trend}).`,
      basis: `complianceMonitor: latestScore=${compliance.latestScore}, trend=${compliance.trend}`,
    });
  }
  if (compliance.openViolationCount > 0) {
    pushRec(recommendations, {
      severity: 'medium',
      title: `${compliance.openViolationCount} logged compliance violation(s) on record`,
      detail: 'See AI Tools → Compliance for the full list.',
      basis: `complianceMonitor: openViolationCount=${compliance.openViolationCount}`,
    });
  }

  const audit = await dependencyAuditor.auditAIDependencies(projectPath);
  if (audit.ok) {
    const behind = audit.dependencies.filter((d) => d.upToDate === false);
    if (behind.length > 0) {
      pushRec(recommendations, {
        severity: 'low',
        title: `${behind.length} AI-related dependenc${behind.length === 1 ? 'y is' : 'ies are'} behind the latest published version`,
        detail: behind.map((d) => `${d.name}: ${d.installedVersion || 'not installed'} → ${d.latestVersion}`).join(', '),
        basis: `dependencyAuditor: ${behind.length} of ${audit.dependencies.length} AI dependencies have installedVersion !== latestVersion`,
      });
    }
  }

  if (recommendations.length === 0) {
    pushRec(recommendations, {
      severity: 'info',
      title: 'Nothing actionable found',
      detail: 'Recorded AI metrics, guardrail results, and dependency versions all look fine against current thresholds.',
      basis: 'no threshold was crossed in aiMetrics, complianceMonitor, or dependencyAuditor data',
    });
  }

  const severityOrder = { high: 0, medium: 1, low: 2, info: 3 };
  recommendations.sort((a, b) => severityOrder[a.severity] - severityOrder[b.severity]);

  return { ok: true, recommendations, generatedAt: new Date().toISOString() };
}

module.exports = { getRecommendations };
